import { toast } from "sonner";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;

/**
 * Triggers a browser download of a certificate PDF generated by the
 * `generate-certificate-pdf` edge function.
 */
export async function downloadCertificatePdf(
  certificateId: string,
  fallbackName = "wattbyte-certificate",
): Promise<void> {
  const url = `${SUPABASE_URL}/functions/v1/generate-certificate-pdf?id=${encodeURIComponent(certificateId)}`;
  const loadingToast = toast.loading("Preparing your certificate…");
  try {
    const res = await fetch(url, { method: "GET" });
    if (!res.ok) {
      let msg = "Failed to generate certificate";
      try {
        const j = await res.json();
        if (j?.error) msg = j.error;
      } catch {
        /* ignore */
      }
      throw new Error(msg);
    }
    const blob = await res.blob();
    const objectUrl = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = objectUrl;
    a.download = `${fallbackName}-${certificateId.slice(0, 8)}.pdf`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    setTimeout(() => URL.revokeObjectURL(objectUrl), 1000);
    toast.dismiss(loadingToast);
    toast.success("Certificate downloaded");
  } catch (err) {
    toast.dismiss(loadingToast);
    toast.error(
      err instanceof Error ? err.message : "Failed to download certificate",
    );
  }
}
