/**
 * Weather Report Translations
 * Supports: English, Chinese (Simplified), Hindi, Arabic, Russian
 */

export type SupportedLanguage = 'en' | 'zh' | 'hi' | 'ar' | 'ru';

export interface WeatherTranslations {
  // Header
  reportTitle: string;
  reportSubtitle: string;
  generated: string;
  platform: string;
  
  // Location & Period
  location: string;
  customLocation: string;
  analysisPeriod: string;
  observations: string;
  
  // Weather Station
  weatherStation: string;
  stationName: string;
  stationId: string;
  elevation: string;
  
  // Executive Summary
  executiveSummary: string;
  temperature: string;
  precipitation: string;
  wind: string;
  average: string;
  maximum: string;
  minimum: string;
  total: string;
  dailyAvg: string;
  daysWithPrecip: string;
  maxGust: string;
  
  // Monthly Breakdown
  monthlyBreakdown: string;
  month: string;
  avgTemp: string;
  totalPrecip: string;
  maxWind: string;
  
  // Data Table
  completeDataTable: string;
  date: string;
  temp: string;
  max: string;
  min: string;
  precip: string;
  rain: string;
  snow: string;
  windSpeed: string;
  page: string;
  of: string;
  
  // Footer
  dataSource: string;
  generatedBy: string;
  
  // Units
  celsius: string;
  mm: string;
  kmh: string;
  meters: string;
}

export const translations: Record<SupportedLanguage, WeatherTranslations> = {
  en: {
    reportTitle: 'Weather Analysis Report',
    reportSubtitle: 'Historical Weather Data Analysis',
    generated: 'Generated',
    platform: 'WattByte Platform',
    location: 'Location',
    customLocation: 'Custom Location',
    analysisPeriod: 'Analysis Period',
    observations: 'observations',
    weatherStation: 'Weather Station',
    stationName: 'Station Name',
    stationId: 'Station ID',
    elevation: 'Elevation',
    executiveSummary: 'Executive Summary',
    temperature: 'Temperature',
    precipitation: 'Precipitation',
    wind: 'Wind',
    average: 'Average',
    maximum: 'Maximum',
    minimum: 'Minimum',
    total: 'Total',
    dailyAvg: 'Daily Avg',
    daysWithPrecip: 'Days w/ Precip',
    maxGust: 'Max Gust',
    monthlyBreakdown: 'Monthly Summary',
    month: 'Month',
    avgTemp: 'Avg Temp',
    totalPrecip: 'Total Precip',
    maxWind: 'Max Wind',
    completeDataTable: 'Complete Weather Data',
    date: 'Date',
    temp: 'Temp',
    max: 'Max',
    min: 'Min',
    precip: 'Precip',
    rain: 'Rain',
    snow: 'Snow',
    windSpeed: 'Wind',
    page: 'Page',
    of: 'of',
    dataSource: 'Data Source: Environment and Climate Change Canada',
    generatedBy: 'Report generated by WattByte Platform',
    celsius: '°C',
    mm: 'mm',
    kmh: 'km/h',
    meters: 'm',
  },
  zh: {
    reportTitle: '天气分析报告',
    reportSubtitle: '历史天气数据分析',
    generated: '生成日期',
    platform: 'WattByte 平台',
    location: '地点',
    customLocation: '自定义位置',
    analysisPeriod: '分析期间',
    observations: '观测记录',
    weatherStation: '气象站',
    stationName: '站名',
    stationId: '站点编号',
    elevation: '海拔',
    executiveSummary: '执行摘要',
    temperature: '温度',
    precipitation: '降水量',
    wind: '风速',
    average: '平均',
    maximum: '最高',
    minimum: '最低',
    total: '总计',
    dailyAvg: '日均',
    daysWithPrecip: '有降水天数',
    maxGust: '最大阵风',
    monthlyBreakdown: '月度汇总',
    month: '月份',
    avgTemp: '平均温度',
    totalPrecip: '总降水量',
    maxWind: '最大风速',
    completeDataTable: '完整天气数据',
    date: '日期',
    temp: '温度',
    max: '最高',
    min: '最低',
    precip: '降水',
    rain: '雨量',
    snow: '雪量',
    windSpeed: '风速',
    page: '第',
    of: '页 / 共',
    dataSource: '数据来源：加拿大环境与气候变化部',
    generatedBy: '报告由 WattByte 平台生成',
    celsius: '°C',
    mm: '毫米',
    kmh: '公里/小时',
    meters: '米',
  },
  hi: {
    reportTitle: 'मौसम विश्लेषण रिपोर्ट',
    reportSubtitle: 'ऐतिहासिक मौसम डेटा विश्लेषण',
    generated: 'जनरेट किया गया',
    platform: 'WattByte प्लेटफॉर्म',
    location: 'स्थान',
    customLocation: 'कस्टम स्थान',
    analysisPeriod: 'विश्लेषण अवधि',
    observations: 'अवलोकन',
    weatherStation: 'मौसम स्टेशन',
    stationName: 'स्टेशन का नाम',
    stationId: 'स्टेशन आईडी',
    elevation: 'ऊंचाई',
    executiveSummary: 'कार्यकारी सारांश',
    temperature: 'तापमान',
    precipitation: 'वर्षा',
    wind: 'हवा',
    average: 'औसत',
    maximum: 'अधिकतम',
    minimum: 'न्यूनतम',
    total: 'कुल',
    dailyAvg: 'दैनिक औसत',
    daysWithPrecip: 'वर्षा वाले दिन',
    maxGust: 'अधिकतम झोंका',
    monthlyBreakdown: 'मासिक सारांश',
    month: 'महीना',
    avgTemp: 'औसत तापमान',
    totalPrecip: 'कुल वर्षा',
    maxWind: 'अधिकतम हवा',
    completeDataTable: 'पूर्ण मौसम डेटा',
    date: 'दिनांक',
    temp: 'तापमान',
    max: 'अधिकतम',
    min: 'न्यूनतम',
    precip: 'वर्षा',
    rain: 'बारिश',
    snow: 'बर्फ',
    windSpeed: 'हवा',
    page: 'पृष्ठ',
    of: 'का',
    dataSource: 'डेटा स्रोत: पर्यावरण और जलवायु परिवर्तन कनाडा',
    generatedBy: 'WattByte प्लेटफॉर्म द्वारा जनरेट की गई रिपोर्ट',
    celsius: '°C',
    mm: 'मिमी',
    kmh: 'किमी/घंटा',
    meters: 'मी',
  },
  ar: {
    reportTitle: 'تقرير تحليل الطقس',
    reportSubtitle: 'تحليل بيانات الطقس التاريخية',
    generated: 'تاريخ الإنشاء',
    platform: 'منصة WattByte',
    location: 'الموقع',
    customLocation: 'موقع مخصص',
    analysisPeriod: 'فترة التحليل',
    observations: 'ملاحظات',
    weatherStation: 'محطة الطقس',
    stationName: 'اسم المحطة',
    stationId: 'معرف المحطة',
    elevation: 'الارتفاع',
    executiveSummary: 'الملخص التنفيذي',
    temperature: 'درجة الحرارة',
    precipitation: 'الهطول',
    wind: 'الرياح',
    average: 'المتوسط',
    maximum: 'الأقصى',
    minimum: 'الأدنى',
    total: 'الإجمالي',
    dailyAvg: 'المتوسط اليومي',
    daysWithPrecip: 'أيام الهطول',
    maxGust: 'أقصى هبة',
    monthlyBreakdown: 'الملخص الشهري',
    month: 'الشهر',
    avgTemp: 'متوسط الحرارة',
    totalPrecip: 'إجمالي الهطول',
    maxWind: 'أقصى رياح',
    completeDataTable: 'بيانات الطقس الكاملة',
    date: 'التاريخ',
    temp: 'الحرارة',
    max: 'الأقصى',
    min: 'الأدنى',
    precip: 'الهطول',
    rain: 'المطر',
    snow: 'الثلج',
    windSpeed: 'الرياح',
    page: 'صفحة',
    of: 'من',
    dataSource: 'مصدر البيانات: البيئة وتغير المناخ كندا',
    generatedBy: 'تم إنشاء التقرير بواسطة منصة WattByte',
    celsius: 'م°',
    mm: 'مم',
    kmh: 'كم/س',
    meters: 'م',
  },
  ru: {
    reportTitle: 'Отчёт о погоде',
    reportSubtitle: 'Анализ исторических данных о погоде',
    generated: 'Создано',
    platform: 'Платформа WattByte',
    location: 'Местоположение',
    customLocation: 'Пользовательское местоположение',
    analysisPeriod: 'Период анализа',
    observations: 'наблюдений',
    weatherStation: 'Метеостанция',
    stationName: 'Название станции',
    stationId: 'ID станции',
    elevation: 'Высота',
    executiveSummary: 'Краткое резюме',
    temperature: 'Температура',
    precipitation: 'Осадки',
    wind: 'Ветер',
    average: 'Среднее',
    maximum: 'Максимум',
    minimum: 'Минимум',
    total: 'Всего',
    dailyAvg: 'Сред. в день',
    daysWithPrecip: 'Дней с осадками',
    maxGust: 'Макс. порыв',
    monthlyBreakdown: 'Месячная сводка',
    month: 'Месяц',
    avgTemp: 'Сред. темп.',
    totalPrecip: 'Всего осадков',
    maxWind: 'Макс. ветер',
    completeDataTable: 'Полные данные о погоде',
    date: 'Дата',
    temp: 'Темп.',
    max: 'Макс.',
    min: 'Мин.',
    precip: 'Осадки',
    rain: 'Дождь',
    snow: 'Снег',
    windSpeed: 'Ветер',
    page: 'Страница',
    of: 'из',
    dataSource: 'Источник данных: Окружающая среда и изменение климата Канады',
    generatedBy: 'Отчёт создан платформой WattByte',
    celsius: '°C',
    mm: 'мм',
    kmh: 'км/ч',
    meters: 'м',
  },
};

export const languageNames: Record<SupportedLanguage, string> = {
  en: 'English',
  zh: '中文',
  hi: 'हिन्दी',
  ar: 'العربية',
  ru: 'Русский',
};

export function getTranslations(language: SupportedLanguage): WeatherTranslations {
  return translations[language] || translations.en;
}

export function formatDateForLanguage(date: string, language: SupportedLanguage): string {
  const d = new Date(date);
  const localeMap: Record<SupportedLanguage, string> = {
    en: 'en-US',
    zh: 'zh-CN',
    hi: 'hi-IN',
    ar: 'ar-SA',
    ru: 'ru-RU',
  };
  
  return d.toLocaleDateString(localeMap[language], {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
}

export function formatMonthForLanguage(date: string, language: SupportedLanguage): string {
  const d = new Date(date + '-01');
  const localeMap: Record<SupportedLanguage, string> = {
    en: 'en-US',
    zh: 'zh-CN',
    hi: 'hi-IN',
    ar: 'ar-SA',
    ru: 'ru-RU',
  };
  
  return d.toLocaleDateString(localeMap[language], {
    year: 'numeric',
    month: 'long',
  });
}

export function formatShortDateForLanguage(date: string, language: SupportedLanguage): string {
  const d = new Date(date);
  const localeMap: Record<SupportedLanguage, string> = {
    en: 'en-US',
    zh: 'zh-CN',
    hi: 'hi-IN',
    ar: 'ar-SA',
    ru: 'ru-RU',
  };
  
  return d.toLocaleDateString(localeMap[language], {
    month: 'short',
    day: 'numeric',
  });
}
