import { Button } from '@/components/ui/button';
import { FileDown } from 'lucide-react';
import jsPDF from 'jspdf';
import { useToast } from '@/hooks/use-toast';

interface ScanReportPDFProps {
  properties: any[];
  location: string;
}

export function ScanReportPDF({ properties, location }: ScanReportPDFProps) {
  const { toast } = useToast();

  const generatePDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    let y = 20;

    // Title
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text('VoltScout Property Scan Report', pageWidth / 2, y, { align: 'center' });
    y += 10;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Location: ${location} · Generated: ${new Date().toLocaleDateString()}`, pageWidth / 2, y, { align: 'center' });
    y += 5;
    doc.text(`Properties Found: ${properties.length}`, pageWidth / 2, y, { align: 'center' });
    y += 12;

    // Line
    doc.setLineWidth(0.5);
    doc.line(15, y, pageWidth - 15, y);
    y += 8;

    // Properties
    for (const prop of properties) {
      if (y > 260) {
        doc.addPage();
        y = 20;
      }

      // Property header
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      const addr = prop.address || `${prop.city}, ${prop.state}`;
      doc.text(addr, 15, y);
      y += 6;

      doc.setFontSize(9);
      doc.setFont('helvetica', 'normal');

      const score = prop.bitcoin_mining_suitability?.score;
      const mw = prop.power_infrastructure?.estimated_power_capacity_mw;
      const price = prop.asking_price;

      const details = [
        `Mining Score: ${score || 'N/A'}/10`,
        `Price: ${price ? `$${(price / 1e6).toFixed(1)}M` : 'N/A'}`,
        `Power: ${mw ? `${mw} MW` : 'N/A'}`,
        `Sq Ft: ${prop.square_footage?.toLocaleString() || 'N/A'}`,
        `Utility: ${prop.power_infrastructure?.utility_provider || 'N/A'}`,
        `Substation: ${prop.power_infrastructure?.substation_distance_miles != null ? `${prop.power_infrastructure.substation_distance_miles} mi` : 'N/A'}`,
      ];

      doc.text(details.join(' · '), 15, y, { maxWidth: pageWidth - 30 });
      y += 5;

      if (prop.description) {
        doc.setFontSize(8);
        const lines = doc.splitTextToSize(prop.description, pageWidth - 30);
        doc.text(lines.slice(0, 2), 15, y);
        y += lines.slice(0, 2).length * 4;
      }

      if (prop.listing_url) {
        doc.setFontSize(7);
        doc.setTextColor(0, 0, 200);
        doc.text(prop.listing_url, 15, y);
        doc.setTextColor(0, 0, 0);
        y += 4;
      }

      // Separator
      y += 4;
      doc.setDrawColor(200, 200, 200);
      doc.line(15, y, pageWidth - 15, y);
      y += 6;
    }

    // Footer
    doc.setFontSize(7);
    doc.text('Generated by VoltScout · volt-site-seeker.lovable.app', pageWidth / 2, 290, { align: 'center' });

    doc.save(`voltscout-scan-${location.replace(/\s+/g, '-').toLowerCase()}-${Date.now()}.pdf`);

    toast({ title: 'PDF Downloaded', description: `Report with ${properties.length} properties saved.` });
  };

  if (properties.length === 0) return null;

  return (
    <Button variant="outline" size="sm" onClick={generatePDF} className="gap-1">
      <FileDown className="w-3 h-3" />
      Export PDF
    </Button>
  );
}
