-- Add 35 more realistic listings
INSERT INTO public.voltmarket_listings (seller_id, listing_type, title, description, location, power_capacity_mw, asking_price, is_featured, views_count, status, property_type, facility_tier, available_power_mw, power_rate_per_kw, cooling_type, hosting_types, minimum_commitment_months, specs) VALUES
-- Data Center Sites
((SELECT id FROM voltmarket_profiles WHERE company_name = 'GreenTech Energy Solutions' LIMIT 1), 'site_sale', 'Premium Data Center Site - Phoenix', 'Fully permitted 250MW data center development site with existing electrical infrastructure. Tier III design specifications with dual power feeds and redundant cooling systems.', 'Phoenix, Arizona', 250, 45000000, true, 1247, 'active', 'data_center', 'tier_3', 250, 0.065, 'evaporative', ARRAY['mining', 'ai_training', 'hpc'], 12, '{"land_acres": 50, "building_sqft": 500000, "redundancy": "2N", "fiber_providers": 5}'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Industrial Power Corp' LIMIT 1), 'site_sale', 'Industrial Manufacturing Facility', '150MW industrial site with heavy power infrastructure. Perfect for manufacturing, data processing, or cryptocurrency mining.', 'Austin, Texas', 150, 28000000, true, 892, 'active', 'industrial', 'tier_2', 150, 0.058, 'air', ARRAY['mining', 'manufacturing'], 6, '{"building_sqft": 500000, "ceiling_height_ft": 32, "loading_docks": 24}'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Solar Dynamics Inc' LIMIT 1), 'site_lease', 'Solar Farm Development Site', 'Prime 500-acre solar development site with completed interconnection studies. Grid-ready location with excellent solar irradiance.', 'Nevada', 200, 5500000, false, 456, 'active', 'land', NULL, 200, 0.045, NULL, NULL, 24, '{"land_acres": 500, "solar_irradiance": "7.2 kWh/m2/day", "grid_distance_miles": 2.5}'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Grid Infrastructure Group' LIMIT 1), 'site_sale', 'Warehouse Conversion Opportunity', '75MW warehouse facility ready for data center conversion. Existing power infrastructure and fiber backbone.', 'Virginia', 75, 18500000, false, 623, 'active', 'warehouse', 'tier_2', 75, 0.072, 'air', ARRAY['ai_training', 'hpc'], 6, '{"building_sqft": 300000, "ceiling_height_ft": 28, "fiber_ready": true}'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Geothermal Energy Corp' LIMIT 1), 'site_sale', 'Geothermal Power Plant Site', '45MW geothermal development site with proven resource and permits. Ready for construction with environmental approvals.', 'California', 45, 22000000, true, 789, 'active', 'industrial', NULL, 45, 0.035, NULL, NULL, 36, '{"resource_temp_c": 185, "flow_rate_kg_s": 120, "environmental_permits": "complete"}');

-- Equipment Listings
INSERT INTO public.voltmarket_listings (seller_id, listing_type, title, description, location, power_capacity_mw, asking_price, is_featured, views_count, status, equipment_type, brand, model, specs, equipment_condition, manufacture_year, quantity, shipping_terms) VALUES
((SELECT id FROM voltmarket_profiles WHERE company_name = 'Wind Power Systems' LIMIT 1), 'equipment', 'Vestas V90 Wind Turbine Portfolio', 'Portfolio of 25 Vestas V90 3MW wind turbines. Excellent condition with full service history.', 'Kansas', 75, 18500000, true, 934, 'active', 'other', 'Vestas', 'V90-3.0MW', '{"rotor_diameter_m": 90, "hub_height_m": 105, "rated_power_mw": 3.0}', 'used', 2018, 25, 'Buyer arranges pickup'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Battery Storage Solutions' LIMIT 1), 'equipment', 'Tesla Megapack Battery Systems', '50MWh Tesla Megapack battery storage system. Grid-scale energy storage for frequency regulation.', 'California', 25, 12000000, true, 1456, 'active', 'other', 'Tesla', 'Megapack', '{"capacity_mwh": 50, "warranty_years": 10, "efficiency_percent": 92.5}', 'new', 2023, 2, 'Installation included'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Turbine Technologies' LIMIT 1), 'equipment', 'GE 1.5MW Wind Turbines', 'Refurbished GE 1.5MW wind turbines. Complete overhaul with new gearboxes and generators.', 'Iowa', 15, 2800000, false, 345, 'active', 'other', 'GE', '1.5sl', '{"rotor_diameter_m": 77, "hub_height_m": 80, "rated_power_mw": 1.5}', 'refurbished', 2015, 10, 'FOB facility'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Solar Panel Distributors' LIMIT 1), 'equipment', 'Tier-1 Solar Panels - Bulk Lot', '500kW of premium Tier-1 solar panels. Perfect for utility-scale installations.', 'Texas', 0.5, 185000, false, 234, 'active', 'other', 'JinkoSolar', 'Tiger Pro', '{"panel_watts": 540, "efficiency_percent": 21.2, "warranty_years": 25}', 'new', 2024, 925, 'Freight included'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Battery Storage Solutions' LIMIT 1), 'equipment', 'Grid-Scale Inverters', 'Power electronics for large-scale renewable integration. High efficiency string inverters.', 'North Carolina', 10, 850000, false, 167, 'active', 'other', 'SMA', 'Sunny Central', '{"rated_power_mw": 2.5, "efficiency_percent": 98.7, "grid_codes": "IEEE 1547"}', 'new', 2024, 4, 'Installation support available');

-- More site listings
INSERT INTO public.voltmarket_listings (seller_id, listing_type, title, description, location, power_capacity_mw, asking_price, is_featured, views_count, status, property_type, facility_tier, available_power_mw, power_rate_per_kw, cooling_type, hosting_types, minimum_commitment_months, specs) VALUES
((SELECT id FROM voltmarket_profiles WHERE company_name = 'Hydropower Innovations' LIMIT 1), 'site_sale', 'Small Hydro Power Plant', '8MW run-of-river hydro facility with long-term water rights. Established plant with modernization opportunity.', 'Oregon', 8, 12500000, false, 445, 'active', 'industrial', NULL, 8, 0.028, NULL, NULL, 60, '{"water_rights": "perpetual", "head_meters": 45, "flow_rate_cms": 25}'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Biomass Power Solutions' LIMIT 1), 'site_sale', 'Biomass Power Facility', '25MW biomass power plant with fuel supply agreements. Waste-to-energy facility with environmental benefits.', 'Alabama', 25, 32000000, false, 556, 'active', 'industrial', NULL, 25, 0.085, NULL, NULL, 36, '{"fuel_type": "wood_waste", "fuel_contract_years": 15, "emissions_controls": "complete"}'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Regional Power Authority' LIMIT 1), 'site_sale', 'Natural Gas Peaker Plant', '100MW natural gas peaking facility. Fast-start capability for grid reliability services.', 'New York', 100, 42000000, true, 678, 'active', 'industrial', NULL, 100, 0.095, NULL, NULL, 24, '{"heat_rate_btu_kwh": 9800, "start_time_minutes": 10, "fuel_type": "natural_gas"}'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Energy Storage Dynamics' LIMIT 1), 'hosting', 'Co-location Data Center Space', 'Premium co-location facility with 50MW available capacity. Tier III certified with 99.99% uptime SLA.', 'Dallas, Texas', 50, 2500000, true, 789, 'active', 'data_center', 'tier_3', 50, 0.068, 'liquid', ARRAY['ai_training', 'hpc', 'mining'], 12, '{"cabinet_count": 500, "cross_connects": "unlimited", "bandwidth_options": "10G/100G"}'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Grid Infrastructure Group' LIMIT 1), 'site_lease', 'Transmission Substation Land', '50-acre site adjacent to major transmission substation. Perfect for utility-scale renewable development.', 'Colorado', 300, 8500000, false, 234, 'active', 'land', NULL, 300, 0.042, NULL, NULL, 36, '{"substation_voltage_kv": 345, "transmission_lines": 3, "wind_resource_class": 4}');

-- Additional equipment and hosting listings
INSERT INTO public.voltmarket_listings (seller_id, listing_type, title, description, location, power_capacity_mw, asking_price, is_featured, views_count, status, equipment_type, brand, model, specs, equipment_condition, manufacture_year, quantity, shipping_terms) VALUES
((SELECT id FROM voltmarket_profiles WHERE company_name = 'Turbine Technologies' LIMIT 1), 'equipment', 'Siemens Wind Turbine Generators', 'High-efficiency wind turbine generators with advanced control systems.', 'Minnesota', 30, 8500000, false, 345, 'active', 'generator', 'Siemens', 'SWT-2.3-108', '{"rotor_diameter_m": 108, "rated_power_mw": 2.3, "cut_in_speed_ms": 3}', 'used', 2019, 13, 'Disassembly included'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Solar Panel Distributors' LIMIT 1), 'equipment', 'Utility-Scale Solar Inverters', 'Central inverters for large solar installations. High efficiency and grid compliance.', 'Arizona', 20, 1200000, false, 223, 'active', 'other', 'Schneider Electric', 'PVSI-100kW', '{"rated_power_kw": 100, "efficiency_percent": 98.8, "operating_temp_c": "40 to 60"}', 'new', 2024, 200, 'Freight prepaid'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Battery Storage Solutions' LIMIT 1), 'equipment', 'Grid Stabilization Battery Bank', 'Large-scale lithium-ion battery system for grid frequency regulation and peak shaving.', 'Illinois', 15, 6800000, true, 567, 'active', 'other', 'LG Chem', 'RESU-500', '{"capacity_mwh": 30, "cycle_life": 6000, "response_time_ms": 100}', 'new', 2023, 1, 'Turnkey installation'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Solar Panel Distributors' LIMIT 1), 'equipment', 'High-Efficiency Solar Modules', 'Premium bifacial solar panels with industry-leading efficiency ratings.', 'Nevada', 2, 950000, false, 189, 'active', 'other', 'LONGi', 'Hi-MO X6', '{"panel_watts": 585, "efficiency_percent": 22.8, "bifacial_factor": 85}', 'new', 2024, 3420, 'Rail delivery available');

-- More hosting and site lease opportunities
INSERT INTO public.voltmarket_listings (seller_id, listing_type, title, description, location, power_capacity_mw, asking_price, is_featured, views_count, status, property_type, facility_tier, available_power_mw, power_rate_per_kw, cooling_type, hosting_types, minimum_commitment_months, specs) VALUES
((SELECT id FROM voltmarket_profiles WHERE company_name = 'Industrial Power Corp' LIMIT 1), 'hosting', 'High-Density Computing Hosting', 'Specialized hosting for AI and HPC workloads. Liquid cooling and high-density configurations.', 'Washington', 35, 1750000, true, 892, 'active', 'data_center', 'tier_3', 35, 0.055, 'liquid', ARRAY['ai_training', 'hpc'], 18, '{"gpu_optimized": true, "liquid_cooling": "direct_chip", "network_fabric": "InfiniBand"}'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Energy Storage Dynamics' LIMIT 1), 'site_lease', 'Energy Storage Development Site', '100-acre site perfect for utility-scale battery storage development.', 'Utah', 200, 12000000, false, 334, 'active', 'land', NULL, 200, 0.038, NULL, NULL, 48, '{"grid_connection": "ready", "environmental_study": "complete", "zoning": "approved"}'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Geothermal Energy Corp' LIMIT 1), 'site_sale', 'Enhanced Geothermal Site', 'Deep geothermal resource with enhanced geothermal system potential.', 'Idaho', 30, 28000000, true, 445, 'active', 'land', NULL, 30, 0.032, NULL, NULL, 60, '{"depth_meters": 3000, "reservoir_temp_c": 200, "egs_potential": "high"}'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Wind Power Systems' LIMIT 1), 'site_lease', 'Wind Farm Development Site', '2,500-acre wind development site with excellent wind resource and grid access.', 'Wyoming', 500, 45000000, true, 667, 'active', 'land', NULL, 500, 0.041, NULL, NULL, 60, '{"wind_speed_ms": 8.5, "turbine_capacity": 500, "transmission_distance_miles": 5}'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Solar Dynamics Inc' LIMIT 1), 'hosting', 'Solar-Powered Data Center', 'Sustainable data center powered by on-site solar with battery backup.', 'California', 40, 2000000, true, 723, 'active', 'data_center', 'tier_2', 40, 0.048, 'evaporative', ARRAY['mining', 'ai_training'], 24, '{"solar_capacity_mw": 60, "battery_storage_mwh": 80, "pue": 1.15}');

-- Final batch of diverse listings
INSERT INTO public.voltmarket_listings (seller_id, listing_type, title, description, location, power_capacity_mw, asking_price, is_featured, views_count, status, property_type, facility_tier, available_power_mw, power_rate_per_kw, cooling_type, hosting_types, minimum_commitment_months, specs) VALUES
((SELECT id FROM voltmarket_profiles WHERE company_name = 'Hydropower Innovations' LIMIT 1), 'site_lease', 'Micro-Hydro Development Rights', 'Water rights and development permits for multiple small hydro sites.', 'Montana', 12, 8500000, false, 234, 'active', 'other', NULL, 12, 0.025, NULL, NULL, 84, '{"sites_count": 6, "combined_capacity_mw": 12, "water_rights": "perpetual"}'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Biomass Power Solutions' LIMIT 1), 'equipment', 'Biomass Gasification System', 'Complete biomass gasification and power generation system.', 'Georgia', 5, 3200000, false, 156, 'active', 'generator', 'Ankur Scientific', 'WBG-1000', '{"biomass_consumption_tpd": 24, "gas_calorific_value": 4500, "electrical_efficiency": 28}', 'refurbished', 2020, 1, 'Installation training included'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Regional Power Authority' LIMIT 1), 'site_sale', 'Decommissioned Coal Plant Site', 'Former coal plant site with existing transmission infrastructure. Ideal for renewable conversion.', 'West Virginia', 400, 85000000, true, 1234, 'active', 'industrial', NULL, 400, 0.035, NULL, NULL, 36, '{"transmission_voltage_kv": 500, "cooling_water_access": true, "rail_access": true}'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Energy Real Estate Specialists' LIMIT 1), 'site_sale', 'Prime Industrial Development Land', '200-acre industrial site with heavy power allocation. Shovel-ready for energy projects.', 'Ohio', 180, 25000000, false, 445, 'active', 'land', NULL, 180, 0.062, NULL, NULL, 12, '{"zoning": "heavy_industrial", "utilities": "all_available", "rail_spur": "existing"}'),

((SELECT id FROM voltmarket_profiles WHERE company_name = 'Power Asset Brokers' LIMIT 1), 'site_sale', 'Portfolio of Solar Sites', 'Package deal: 5 solar development sites across multiple states.', 'Multi-State', 1000, 125000000, true, 1789, 'active', 'land', NULL, 1000, 0.039, NULL, NULL, 48, '{"sites_count": 5, "states": ["Texas", "Arizona", "Nevada", "California", "New Mexico"], "total_acres": 3500}');